def ex7(n : int):
    '''
    function for generating the set M with the following rules:
        1. 1 is in M
        2. if x is in M, then 2x+1 and 3x+1 are in M
        3. M doesn't contain other elements
    :param n: int
    '''
    m = {1} # we start with the initial element
    result = [] # we initialize the result list

    while len(result) < n: # as long as we have less than n elements in the result list
        x = min(m) # we pick the smallest element
        result.append(x) # we add it to the result list
        m.remove(x) # we remove it from M to not consider it in the next loop

        m.add(2 * x + 1) #
        m.add(3 * x + 1)  # we add the elements generated by x to the set M
    print(*result, sep = ', ') # print
if __name__ == '__main__':
    n = int(input('n = ')) # accept input
    ex7(n)
